export const projects = [
  {
    date: "2020-12-01",
    title: "Course grader",
    github: "https://github.com/einargudnig/courseAdvisor",
    external: "https://course-advisor-csui.herokuapp.com/",
    tech1: "Firebase",
    tech2: "React",
    tech3: "Material-Ui",
    company: "",
    text:
      "Web application built with React and Firebase database. Allows students from the Computer Science department from the University of Iceland to review and grade their classes.",
  },
  {
    date: "2019-04-01",
    title: "Reboothack.is",
    github: "https://github.com/einargudnig/reboothackFORK",
    external: "https://reboothack.is",
    tech1: "React",
    tech2: "PostgreSQL",
    tech3: "Node",
    company: "",
    text:
      "Information and registration webpage for Reboot Hack, the first student driven hackathon in Iceland. Built with React, PostgreSQL and Node.",
  },
  {
    date: "2017-12-01",
    title: "GAIA",
    github: "https://github.com/einargudnig/GAIA",
    external: "",
    tech1: "Java Spring",
    tech2: "PostgreSQL",
    tech3: "HTML",
    company: "",
    text:
      "Web application built with Java Spring and Thymeleaf HTML templates, Makes users complete challenges to decrease their carbon footprint.",
  },
  {
    date: "2018-05-01",
    title: "GAIA v2.0",
    github: "https://github.com/einargudnig/GAIA-2.0",
    external: "",
    tech1: "JAVA",
    tech2: "RESTful APIs",
    tech3: "Android Studio",
    company: "",
    text:
      "Android app built to use a RESTful API. Users make their own profile that calculates their carbon footprint. Users can complete challenges to decrease their carbon footprint.",
  },
  {
    date: "2020-04-15",
    title: "Grade Checker",
    github: "https://github.com/einargudnig/gradeScraper",
    external: "",
    tech1: "Python",
    tech2: "Selenium",
    tech3: "",
    company: "",
    text:
      "Simple python scripts that logs in to my University of Iceland account to check if I have received my exam grades, if I have then it sends me an email.",
  },
  {
    date: "2018-03-27",
    title: "NFL Pick-em",
    github: "https://github.com/einargudnig/nflWebService",
    external: "",
    tech1: "NodeJS",
    tech2: "Express",
    tech3: "PostgreSQL",
    company: "",
    text:
      "Webservice for a NFL pick-em game. Gets the schedule from NFL, lets the user choose the winner. Has working authentication. Plan is to build a React or Typescript front end to work with his project.",
  },
  {
    date: "2018-06-25",
    title: "Personal website 1.0",
    github: "https://github.com/einargudnig/homePage",
    external: "",
    tech1: "Gatsby",
    tech2: "",
    tech3: "",
    company: "",
    text: "First version of my personal website",
  },
  {
    date: "2019-05-04",
    title: "Personal website 2.0",
    github: "https://github.com/einargudnig/homepage2.0",
    external: "",
    tech1: "Gastby",
    tech2: "GraphQl",
    tech3: "CSS",
    company: "",
    text: "Second version of my personal website",
  },
];
